[build]
  command = "npm install && npm run build:all"
  publish = "dist"

[functions]
  directory = "netlify/functions-built"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
