import { GoogleGenAI, Modality } from "@google/genai";

// Helper function to convert a File object to a base64 string
const fileToBase64 = (file: File): Promise<string> => {
    return new Promise((resolve, reject) => {
      const reader = new FileReader();
      reader.readAsDataURL(file);
      reader.onload = () => {
        const result = reader.result as string;
        resolve(result.split(',')[1]);
      };
      reader.onerror = (error) => reject(error);
    });
};

// This function calls the Gemini API directly and is used for local/preview development
const stitchImagesLocally = async (image1File: File, image2File: File, prompt: string): Promise<string> => {
    const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });

    const image1Base64 = await fileToBase64(image1File);
    const image2Base64 = await fileToBase64(image2File);

    const image1Part = {
      inlineData: {
        data: image1Base64,
        mimeType: image1File.type,
      },
    };
    
    const image2Part = {
      inlineData: {
        data: image2Base64,
        mimeType: image2File.type,
      },
    };

    const textPart = {
      text: `Stitch these two images together. Image 1 is the primary context unless specified otherwise. Instruction: ${prompt}`,
    };

    const response = await ai.models.generateContent({
      model: 'gemini-2.5-flash-image',
      contents: {
        parts: [image1Part, image2Part, textPart],
      },
      config: {
        responseModalities: [Modality.IMAGE],
      },
    });

    for (const part of response.candidates?.[0]?.content?.parts || []) {
        if (part.inlineData) {
          const mimeType = part.inlineData.mimeType;
          const base64ImageBytes: string = part.inlineData.data;
          return `data:${mimeType};base64,${base64ImageBytes}`;
        }
    }

    throw new Error("No image was generated by the model.");
}

// This function calls the secure Netlify function and is used for production
const stitchImagesOnNetlify = async (image1File: File, image2File: File, prompt: string): Promise<string> => {
    const image1Base64 = await fileToBase64(image1File);
    const image2Base64 = await fileToBase64(image2File);

    const endpoint = '/.netlify/functions/stitch';

    const response = await fetch(endpoint, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        image1: { base64: image1Base64, mimeType: image1File.type },
        image2: { base64: image2Base64, mimeType: image2File.type },
        prompt: prompt,
      }),
    });
    
    const data = await response.json();

    if (!response.ok) {
        throw new Error(data.error || 'An error occurred on the server.');
    }
    if (!data.imageUrl) {
        throw new Error('Server did not return an image URL.');
    }
    
    return data.imageUrl;
}


// Universal stitchImages function that decides which method to use
export const stitchImages = async (image1File: File, image2File: File, prompt: string): Promise<string> => {
  try {
    // Check if API_KEY is available on the client-side (dev/preview environment)
    if (process.env.API_KEY) {
      console.log("Running in development/preview mode. Calling Gemini API directly.");
      return await stitchImagesLocally(image1File, image2File, prompt);
    } else {
      console.log("Running in production mode. Calling Netlify function.");
      return await stitchImagesOnNetlify(image1File, image2File, prompt);
    }
  } catch (error) {
    console.error("Error during image stitching:", error);
    const errorMessage = error instanceof Error ? error.message : "An unknown error occurred.";
    throw new Error(`Failed to stitch images: ${errorMessage}`);
  }
};
