import { GoogleGenAI, Modality } from "@google/genai";
import { UploadedImage } from './types';

// Helper function to convert a File object to a base64 string
const fileToBase64 = (file: File): Promise<string> => {
    return new Promise((resolve, reject) => {
      const reader = new FileReader();
      reader.readAsDataURL(file);
      reader.onload = () => {
        const result = reader.result as string;
        // remove the "data:image/jpeg;base64," part
        resolve(result.split(',')[1]); 
      };
      reader.onerror = (error) => reject(error);
    });
};

// This function calls the Netlify function, which in turn calls the Gemini API.
const stitchImagesViaNetlify = async (
  image1File: File,
  image2File: File,
  prompt: string,
): Promise<string> => {
  const image1Base64 = await fileToBase64(image1File);
  const image2Base64 = await fileToBase64(image2File);

  const response = await fetch('/.netlify/functions/stitch', {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
    },
    body: JSON.stringify({
      image1: { base64: image1Base64, mimeType: image1File.type },
      image2: { base64: image2Base64, mimeType: image2File.type },
      prompt: prompt,
    }),
  });

  if (!response.ok) {
    const errorData = await response.json();
    throw new Error(errorData.error || `Request failed with status ${response.status}`);
  }

  const result = await response.json();
  return result.imageUrl;
};

// This function calls Gemini API directly, for use in AI Studio
const stitchImagesDirectly = async (
    image1File: File,
    image2File: File,
    prompt: string,
): Promise<string> => {
    const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });

    const image1Base64 = await fileToBase64(image1File);
    const image2Base64 = await fileToBase64(image2File);

    const image1Part = {
        inlineData: {
          data: image1Base64,
          mimeType: image1File.type,
        },
    };
      
    const image2Part = {
        inlineData: {
          data: image2Base64,
          mimeType: image2File.type,
        },
    };
  
    const textPart = {
        text: `Stitch these two images together. Image 1 is the primary context unless specified otherwise. Instruction: ${prompt}`,
    };

    const response = await ai.models.generateContent({
        model: 'gemini-2.5-flash-image',
        contents: {
          parts: [image1Part, image2Part, textPart],
        },
        config: {
          responseModalities: [Modality.IMAGE],
        },
    });

    for (const part of response.candidates?.[0]?.content?.parts || []) {
        if (part.inlineData?.data) {
          const mimeType = part.inlineData.mimeType;
          const base64ImageBytes: string = part.inlineData.data;
          return `data:${mimeType};base64,${base64ImageBytes}`;
        }
    }

    throw new Error("No image was generated by the model.");
}

// The main export function that decides which path to take.
export const stitchImages = async (
    image1File: File,
    image2File: File,
    prompt: string,
): Promise<string> => {
    // Check if we are in an environment like AI Studio that provides the API key directly
    if (typeof process !== 'undefined' && process.env.API_KEY) {
        try {
            return await stitchImagesDirectly(image1File, image2File, prompt);
        } catch (error) {
            console.error("Direct API call failed:", error);
            const errorMessage = error instanceof Error ? error.message : "An unknown error occurred.";
            throw new Error(`Failed to stitch images: ${errorMessage}`);
        }
    } else {
        // Assume we are in a production environment like Netlify and use the serverless function
         try {
            return await stitchImagesViaNetlify(image1File, image2File, prompt);
        } catch (error) {
            console.error("Netlify function call failed:", error);
            const errorMessage = error instanceof Error ? error.message : "An unknown error occurred.";
            throw new Error(`Failed to stitch images: ${errorMessage}`);
        }
    }
}
